# 全局配置
runmode: release
addr: :8080
name: lemon
url: http://127.0.0.1:8080

# 日志存储路径

# 生成jwt的密钥
jwt_secret: XQiOjE1MjgwMTY5MjIsImlkIjowL
# 生成签名的密钥
sign_secret: 8D0C7OoCjQ4BViKSGqa4NBsSyuN

# 日志配置
log:
  file_path: /Users/liangjian/code/github/src/lemon/logs/

# 数据库配置
local_db:
  name: go
  addr: 127.0.0.1:3306
  username: root
  password: 123456
