# 全局配置
runmode: release
addr: :8080
name: lemon
url: http://127.0.0.1:8080

# 日志存储路径

# 生成jwt的密钥
jwt_secret: XQiOjE1MjgwMTY5MjIsImlkIjowL
# 生成签名的密钥
sign_secret: 8D0C7OoCjQ4BViKSGqa4NBsSyuN

# 日志配置
log:
  file_path: /Users/liangjian/code/github/lemon/logs/
  writers: stdout
  logger_level: DEBUG
  logger_file: logs/log.log
  log_format_text: true
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7

# 数据库配置
local_db:
  name: go
  addr: 127.0.0.1:3306
  username: root
  password: 123456
